<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>apply score rate</name>
  <uuid>2cfa0be4-6c93-4016-b2d2-4dee1f8b8cef</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to round ( decision * 'Score rate', 0 );]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
