<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>defaulted score</name>
  <uuid>e36c62c4-ae84-4078-9850-e9337410f8cd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Client is Defaulted Payment
then
	add -1 to decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
