<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>services score</name>
  <uuid>b7e426e2-032f-473d-8056-5541afc6aa9f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the number of elements in the Services Requesteds of Services is more than 3
then 
add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
